# Generated by Django 3.2.4 on 2021-07-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20, verbose_name='Nombre')),
                ('apellido_pat', models.TextField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_mat', models.TextField(max_length=20, verbose_name='Apellido Materno')),
                ('genero', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], verbose_name='Genero')),
                ('fecha_nac', models.DateTimeField(verbose_name='Fecha Nacimiento')),
                ('usuario', models.TextField(max_length=20, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=24, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['created'],
            },
        ),
    ]
