# Generated by Django 3.2.4 on 2021-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20210711_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='apellido_mat',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='apellido_pat',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
