# Generated by Django 3.2.4 on 2021-07-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
