# Generated by Django 3.2.4 on 2021-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('subcategoria', models.CharField(max_length=20, verbose_name='Subcategoria')),
                ('color', models.CharField(max_length=20, verbose_name='Color Producto')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=20, verbose_name='Descripcion Producto')),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Cantidad')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['created'],
            },
        ),
    ]
