# Generated by Django 3.2.4 on 2021-08-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre Producto'),
        ),
    ]
