# Generated by Django 3.2.4 on 2021-08-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=8, verbose_name='Password')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('cliente', models.TextField(verbose_name='Cliente')),
                ('asunto', models.TextField(verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Cliente',
                'verbose_name_plural': 'Comentarios Cliente',
                'ordering': ['-created'],
            },
        ),
    ]
