# Generated by Django 3.2.4 on 2021-08-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_auto_20210825_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='usuarios',
        ),
    ]
