# Generated by Django 3.2.4 on 2021-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0018_rename_admin_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido_pat', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_mat', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('fecha_nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=24, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
