# Generated by Django 3.2.4 on 2021-08-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_auto_20210825_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
    ]
